
method: CaDeX-ATC-eyeglasses-pcl
gpu: 6, 7
modes: ["train", "val"]

model:
  model_name: cadex_pm
  loss_theta: False

dataset:
  pin_mem: False
  dataset_name: partMobility
  data_root: ./resource/data/partMobility/base_data/train/eyeglasses
  dataset_proportion: [1.0, 1.0]
  num_workers: 10
  input_type: "pcl"

  rotate_augmentation: False
  translate_augmentation: True
  scale_augmentation: True
  input_num: 4
  num_atc: 2

  num_input_pts: 2048
  input_noise: 0.002
  theta_range: [[-30, 30], [-30, 30]]

training:
  grad_clip: -1
  loss_clip: -1
  optim:
    all:
      lr: 0.001
      decay_schedule: [150, 200, 250, 300]
      decay_factor: [0.5, 0.5, 0.5, 0.5]
      lr_min: 0.000001
  loss_axis: False
  refinement_point_n: 200
  dcd_alpha: 10
  dcd_threshold: 1
  total_epoch: 1001
  batch_size: 6
  ablation: True
  
evaluation:
  eval_every_epoch: 50
  batch_size: 4

logging:
  log_dir: cadex_pm_eyeglasses_pcl_double
  loggers: ["image", "hist", "video", "xls"]
  viz_training_batch_interval: 5
  viz_nontrain_batch_interval: 5
  viz_epoch_interval: 50
  checkpoint_epoch: 50
  mesh_viz_interval: 1

  model_select_metric: segmentation
  model_select_larger: true